#!/bin/sh

# PROVIDE: breachblocker
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="breachblocker"
prefix="bb"
rcvar="breachblocker_enable"

# please update the needed command and bbpath paths below to match
# your python executable and .py path
command="/usr/local/bin/python3.6"
bbpath="/root/breachblocker/breachblocker.py"

# please make sure tho given PID file is the same as in the
# breachblocker config file
pidfile="/var/run/breachblocker.pid"

start_cmd="${prefix}_start"
stop_cmd="${prefix}_stop"
restart_cmd="${prefix}_restart"
status_cmd="${prefix}_status"

bb_start() {
   echo "Breachblocker starting..."
   $command $bbpath
}

bb_stop() {
   $command $bbpath --kill
}

bb_restart() {
   bb_stop
   bb_start
}

bb_status() {
    if [ ! -e $pidfile ]; then
        echo "PID file seems to not exist. Something wrong or not started?"
    else
        pid=`cat $pidfile`
        echo "Breachblocker is running... PID $pid"
    fi
}

load_rc_config $name
run_rc_command "$1"

# eof
